# Generated by Django 5.0.6 on 2024-06-28 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wuming', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='uploads/banners/')),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('link', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Banners',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
